ParrisConnection/Controllers/SingleStatusController.cs
using Microsoft.AspNet.Identity;
using ParrisConnection.ServiceLayer.Data;
using ParrisConnection.ServiceLayer.Services.Status.Save;
using System.Web.Mvc;

namespace ParrisConnection.Controllers
{
    public class SingleStatusController : Controller
    {
        private readonly IStatusSaveService _statusSaveService;

        public SingleStatusController(IStatusSaveService statusSaveService)
        {
            _statusSaveService = statusSaveService;
        }


        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddStatus(StatusData status)
        {
            status.UserId = User != null ? User.Identity.GetUserId() : "";
           _statusSaveService.SaveStatus(status);

            return RedirectToAction("Index", "Wall");
        }
    }
}

ParrisConnection/Views/SingleStatus/Index.cshtml
@model ParrisConnection.ServiceLayer.Data.StatusData

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-5">
            @using (Html.BeginForm("AddStatus", "SingleStatus"))
            {
                <div class="form-group">
                    @Html.TextAreaFor(s => s.Post, new { @class = "form-control" })
                </div>
                <button type="submit" class="btn btn-primary">Update Status</button>
            }
        </div>
    </div>
</div>